# Generated by Django 5.0.2 on 2024-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_authuser_picture_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='department',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
