# Generated by Django 5.0.2 on 2024-03-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_department_faculty_subject_and_more'),
        ('Home', '0003_remove_student_notice_tag_student_notice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_marks', to='Admin.faculty'),
        ),
    ]
