# Generated by Django 5.0.2 on 2024-03-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_rename_department_faculty_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=10000, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attechments', models.FileField(blank=True, null=True, upload_to='assignment_questions/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assignment_questions',
            },
        ),
        migrations.CreateModel(
            name='AssignMents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('attechments', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(related_name='assignment_questions', to='teachers.assignment_questions')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Admin.faculty')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Important_Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attechments', models.FileField(blank=True, null=True, upload_to='important_topics/')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_important_topics', to='Admin.faculty')),
            ],
            options={
                'db_table': 'important_topics',
            },
        ),
    ]
