# Generated by Django 5.0.2 on 2024-03-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_questions',
            old_name='attechments',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='attechments',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='important_topics',
            old_name='attechments',
            new_name='attachments',
        ),
    ]
