# Generated by Django 5.0.2 on 2024-03-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_rename_department_faculty_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attechments', models.FileField(blank=True, null=True, upload_to='student_queries/')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_queries', to='Admin.student')),
            ],
            options={
                'db_table': 'student_queries',
            },
        ),
        migrations.CreateModel(
            name='Student_Queries_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attechments', models.FileField(blank=True, null=True, upload_to='student_query_answers/')),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_query_answers', to='Admin.faculty')),
                ('student_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_query_answers', to='student.student_query')),
            ],
            options={
                'db_table': 'student_queries_answers',
            },
        ),
    ]
